language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t michalboljesik/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true michalboljesik/react-test npm test

after_success:
  - docker build -t michalboljesik/multi-client ./client
  - docker build -t michalboljesik/multi-nginx ./nginx
  - docker build -t michalboljesik/multi-server ./server
  - docker build -t michalboljesik/multi-worker ./worker
  # Take the images and push them to Docker Hub